# fly.toml app configuration file generated for coreinfra on 2025-02-23T19:11:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coreinfra'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[env]]
  DB_HOST='ep-small-salad-a5sed7ma-pooler.us-east-2.aws.neon.tech'
  DB_USER='coreinfra_owner'
  DB_PASSWORD='npg_K3Enpwu9HeRk'
  DB_NAME='coreinfra'
  DB_PORT='5432'
  JWT_SECRET='your_secret_key'
  JWT_EXPIRES_IN='1h'
  # 🌍 Environment
  NODE_ENV='production'

  # 📌 Server Configuration
  PORT='3000'
  # Do not expose your Neon credentials to the browser

  PGHOST='ep-small-salad-a5sed7ma-pooler.us-east-2.aws.neon.tech'
  PGDATABASE='coreinfra'
  PGUSER='coreinfra_owner'
  PGPASSWORD='npg_K3Enpwu9HeRk'

  POSTGRES_DB_URI='postgresql://coreinfra_owner:npg_K3Enpwu9HeRk@ep-small-salad-a5sed7ma-pooler.us-east-2.aws.neon.tech/coreinfra?sslmode=require'
  POSTGRES_LOCAL_DB_URI="postgres://postgres:olaniran@localhost:5432/coreinfra"
